### ISSUE TITLE
[Question] How do I implement this to build something like a sentiment analyzer?

### ISSUE THREAD

**Issue by weirdyang** [orionw/RedditHumorDetection#4]
Hi,

Apologies if this is the wrong place to ask this. I was wondering how do I use this to implement something similar to [vaderSentiment](https://github.com/cjhutto/vaderSentiment) but for humor.

Any advice is appreciated, thanks!

**Comment by orionw** [comment]
Sure, you're welcome to use the model to label sentences as humorous or non-humorous.  Instructions for using the model on sentences are in the README.  You can train the model and then evaluate it on sentences you care about in a new test set.

The implementation in `vaderSentiment` looks like it is actively maintained and more abstract.  This repository was for a unmaintained research project and is based on a 2 year old version of the Huggingface Transformers library - it likely is not as easy to use as `vaderSentiment` , but it should be helpful it you want an example of what you can do.

**Comment by weirdyang** [comment]
Thanks will read through the read me again.
